name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
            node -v
            npm -v
  run-a-parrallel-job:
    runs-on: centos-latest
    steps:
        - name: Check the OS verion
          run: cat /etc/os-release
        - name: Check JDK Version
          run: java -version
  run-a-depend-on:
    runs-on: windows-latest
    needs: run-shell-command
    steps: 
      - name: echo a string
        run: Write-Output "Windows String"
      - name: Error Step
        run: doesnotexits